export const workspace = {
  name: "演示工作区",
  user: "当前用户",
  dataStatus: "演示数据",
  environment: "交互原型",
};

export const tasks = [
  {
    id: "tr_sales_channel",
    title: "本月各渠道支付销售额及主要差异",
    status: "waiting_approval",
    statusLabel: "等待审批",
    channel: "Web",
    updated: "2 分钟前",
    owner: "当前用户",
    progress: 34,
    current: "审核只读 SQL",
    datasource: "销售分析库",
    created: "2026-08-24 22:18",
    question: "统计本月各渠道支付销售额，按金额降序排列，并分析主要差异。",
    scope: "2026-08-01—2026-08-24 · 已支付订单 · 渠道粒度",
    sql: "SELECT\n  channel,\n  SUM(paid_amount) AS paid_sales\nFROM orders\nWHERE status = 'paid'\n  AND paid_at >= :month_start\n  AND paid_at < :month_end\nGROUP BY channel\nORDER BY paid_sales DESC\nLIMIT 200;",
    plan: [
      ["明确问题与范围", "completed", "已确认自然月、已支付口径和渠道粒度"],
      ["准备查询", "completed", "Forge 已完成结构、口径和只读检查"],
      ["审核 SQL", "waiting_approval", "等待当前用户确认执行内容"],
      ["只读执行", "waiting", "审批后最多返回 200 行"],
      ["分析差异", "waiting", "只引用本次查询结果"],
      ["生成报告", "waiting", "交付 HTML、PDF 和 PPTX"],
    ],
    checks: ["只读取 orders", "包含时间范围", "结果上限 200 行", "未使用写入语句"],
  },
  {
    id: "tr_repurchase_definition",
    title: "确认复购率的业务口径",
    status: "needs_input",
    statusLabel: "等待补充",
    channel: "飞书",
    updated: "12 分钟前",
    owner: "当前用户",
    progress: 12,
    current: "确认复购时间窗口",
    question: "查看最近三个月复购率变化。",
    scope: "时间窗口尚未确认",
    plan: [["明确问题与范围", "needs_input", "需要确认复购是否限定在 90 天内"], ["准备查询", "waiting", "等待口径确认"]],
  },
  {
    id: "tr_category_analysis",
    title: "上半年品类结构与增长诊断",
    status: "analyzing",
    statusLabel: "分析中",
    channel: "Web",
    updated: "18 分钟前",
    owner: "当前用户",
    progress: 72,
    current: "整理观察、判断和限制",
    question: "分析上半年品类销售结构、月度目标差异和渠道增量。",
    scope: "2026-01—2026-06 · 销售额",
    plan: [["明确问题与范围", "completed", "范围已确认"], ["准备并审核查询", "completed", "两条查询已执行"], ["分析差异", "running", "正在生成有证据的分析"], ["生成报告", "waiting", "等待分析完成"]],
  },
  {
    id: "tr_weekly_report",
    title: "第 34 周经营周报",
    status: "completed",
    statusLabel: "已完成",
    channel: "飞书",
    updated: "今天 17:42",
    owner: "当前用户",
    progress: 100,
    current: "报告已生成",
    question: "生成本周经营周报并标出异常。",
    scope: "2026-W34 · 日粒度",
    reportId: "rp_week34",
    plan: [["明确问题与范围", "completed", "范围已确认"], ["查询与审批", "completed", "只读查询已执行"], ["分析", "completed", "5 项观察、2 项限制"], ["报告", "completed", "HTML/PDF/PPTX 已生成"]],
  },
  {
    id: "tr_inventory_failure",
    title: "库存周转异常排查",
    status: "failed",
    statusLabel: "失败",
    channel: "API",
    updated: "昨天 16:20",
    owner: "当前用户",
    progress: 38,
    current: "数据源查询超时",
    question: "找出库存周转天数异常的商品。",
    scope: "最近 30 天 · 商品粒度",
    failure: "查询在 30 秒上限到期后停止。SQL 未执行完成，未生成分析或报告。",
    plan: [["明确问题与范围", "completed", "范围已确认"], ["准备查询", "completed", "SQL 已审核"], ["只读执行", "failed", "达到查询超时上限"], ["分析", "waiting", "未启动"]],
  },
  {
    id: "tr_customer_report",
    title: "高价值客户结构报告",
    status: "rendering",
    statusLabel: "生成报告",
    channel: "Web",
    updated: "昨天 11:05",
    owner: "当前用户",
    progress: 88,
    current: "生成 PDF 与 PPTX",
    question: "分析高价值客户结构并生成业务报告。",
    scope: "最近 12 个月 · 客户粒度",
    plan: [["查询与审批", "completed", "已完成"], ["分析", "completed", "已完成"], ["生成报告", "running", "HTML 已完成，静态导出进行中"]],
  },
];

export const reports = [
  { id: "rp_category_h1", title: "品类组合与增长诊断", period: "2026-01—2026-06", status: "ready", statusLabel: "可查看", updated: "今天 22:44", taskId: "tr_category_analysis", formats: ["HTML", "PDF", "PPTX"], summary: "头部品类接近；四月低于目标，五月和六月恢复；四月至六月新增 174K。", revision: "1", quality: "数据未截断" },
  { id: "rp_week34", title: "第 34 周经营周报", period: "2026-W34", status: "ready", statusLabel: "可查看", updated: "今天 17:42", taskId: "tr_weekly_report", formats: ["HTML", "PDF", "PPTX"], summary: "本周销售较上周增长 3.1%，两类商品低于补货安全线。", revision: "2", quality: "1 项限制" },
  { id: "rp_customer_structure", title: "高价值客户结构报告", period: "最近 12 个月", status: "rendering", statusLabel: "生成中", updated: "昨天 11:05", taskId: "tr_customer_report", formats: ["HTML"], summary: "业务报告正文已完成，PDF 与 PPTX 尚在生成。", revision: "1", quality: "静态导出未完成" },
];

export const assets = {
  counts: { tables: 24, metrics: 18, rules: 31, drafts: 2 },
  tables: [
    ["orders", "订单事实表", "18 个字段", "2 小时前"],
    ["order_items", "订单明细表", "12 个字段", "2 小时前"],
    ["customers", "客户主表", "15 个字段", "昨天"],
    ["products", "商品主表", "14 个字段", "昨天"],
  ],
  metrics: [
    ["支付销售额", "SUM(paid_amount)", "订单 · 日", "已发布"],
    ["支付订单数", "COUNT(DISTINCT order_id)", "订单 · 日", "已发布"],
    ["复购率", "复购用户 / 购买用户", "用户 · 月", "待确认"],
    ["库存周转天数", "平均库存 / 销售成本 × 天数", "商品 · 月", "草案"],
  ],
  drafts: [
    ["draft_024", "新增渠道字段约定", "等待审核", "今天 19:30"],
    ["draft_023", "确认 orders → customers 关系", "需要补充", "昨天 15:10"],
  ],
};

export const activity = [
  ["22:18:06", "任务已创建", "来自 Web"],
  ["22:18:08", "问题范围已确认", "自然月、已支付订单、渠道粒度"],
  ["22:18:11", "查询计划已准备", "Registry revision 42"],
  ["22:18:12", "只读检查通过", "4 项检查通过"],
  ["22:18:12", "等待 SQL 审批", "尚未执行数据库查询"],
];
